We can see where we are using system's commands.

In [24]:
! ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


### Opening and reading a txt file

In [25]:
file = open("./huck_finn.txt", mode="r")

In [26]:
print(file.read())
print(file.closed)

CHAPTER I.

YOU don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter. That book was made by Mr. Mark Twain, and he told the truth, mainly. There was things which he stretched, but mainly he told the truth. That is nothing. I never seen anybody but lied one time or another, without it was Aunt Polly, or the widow, or maybe Mary. Aunt Polly--Tom's Aunt Polly, she is--and Mary, and the Widow Douglas is all told about in that book, which is mostly a true book, with some stretchers, as I said before.

Now the way that the book winds up is this: Tom and me found the money that the robbers hid in the cave, and it made us rich. We got six thousand dollars apiece--all gold. It was an awful sight of money when it was piled up. Well, Judge Thatcher he took it and put it out at interest, and it fetched us a dollar a day apiece all the year round --more than a body could tell what to do with. The Widow Douglas she took me for her son

In [27]:
file.close()
print(file.closed)

True


### A better way to opening and closing files

In [30]:
with open("./huck_finn.txt") as file:
    print(file.readline())
    print(file.readline())
    print(file.readline())
    print(file.readline())

CHAPTER I.



YOU don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter. That book was made by Mr. Mark Twain, and he told the truth, mainly. There was things which he stretched, but mainly he told the truth. That is nothing. I never seen anybody but lied one time or another, without it was Aunt Polly, or the widow, or maybe Mary. Aunt Polly--Tom's Aunt Polly, she is--and Mary, and the Widow Douglas is all told about in that book, which is mostly a true book, with some stretchers, as I said before.





### PEPs

[PEP8  — Style Guide for Python Code](https://peps.python.org/pep-0008/)  
[PEP20 — The Zen of Python](https://peps.python.org/pep-0020/)

## Using Numpy

In [31]:
import numpy as np

In [36]:
filename = './mnist_kaggle_some_rows.csv'
fd = np.loadtxt(filename, delimiter=",")
print(fd)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [2. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]]
